apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fullstack-app
type: Opaque
data:
  # Base64 encoded RDS password
  DB_PASSWORD: Y2hhbmdlbWUxMjM0IVNlY3VyZVBhc3M=  # "changeme1234!SecurePass" in base64